#!/bin/bash

PATH_TO_FIND=`pwd`
TAGFILE="TAGS"
OPTS="--extra=+f -a -R -h \".s.S.h.c.cpp.java.py\""
echo "cleaning the previous TAGS files"
rm -f TAGS

while getopts o: o
do
	case "$o" in
		o)
			TAGFILE="$OPTARG";;
		[?])
			echo "Invalid args!!"
			;;
	esac
done
shift $(($OPTIND - 1))

if [ -n "$1" ]; then
	PATH_TO_FIND=$@
fi

echo "PATH: $PATH_TO_FIND"
echo "TAGFILE: $TAGFILE"
echo "OPTS: $OPTS"

etags $OPTS -f $TAGFILE $PATH_TO_FIND

